spring.application.name=SnowBall
# 临时测试：连 MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/snowball?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
spring.datasource.username=YOUR_NAME
spring.datasource.password=YOUR_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 自动建表（开发阶段先用，后面建议关掉或改成 validate）
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
